name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - coverage
  - black
  - python-dotenv>=0.5.1
  - pre_commit

  {% if cookiecutter.install_R == "yes" %}
  - r
  - r-essentials
  {% endif %}
